// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ScheduleGo.Infra.ScheduleGoContext.DataContexts;

namespace ScheduleGo.Engine.Migrations
{
    [DbContext(typeof(ScheduleGoDataContext))]
    partial class ScheduleGoDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ScheduleGo.Domain.ScheduleGoContext.Entities.Classroom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Classrooms");
                });

            modelBuilder.Entity("ScheduleGo.Domain.ScheduleGoContext.Entities.ClassroomType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ClassroomTypes");
                });

            modelBuilder.Entity("ScheduleGo.Domain.ScheduleGoContext.Entities.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentsCount")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("WeeklyWorkload")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("ScheduleGo.Domain.ScheduleGoContext.Entities.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("ScheduleGo.Domain.ScheduleGoContext.Entities.Teacher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("ScheduleGo.Domain.ScheduleGoContext.Entities.TimePeriod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("End")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("TimePeriods");
                });

            modelBuilder.Entity("ScheduleGo.Shared.ScheduleGoContext.Entities.LinkEntity<ScheduleGo.Domain.ScheduleGoContext.Entities.Classroom, ScheduleGo.Domain.ScheduleGoContext.Entities.ClassroomType>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("LeftId")
                        .HasColumnName("Classroom")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RightId")
                        .HasColumnName("ClassroomType")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RightId")
                        .IsUnique();

                    b.ToTable("ClassroomClassroomType");

                    b.HasDiscriminator<string>("Discriminator").HasValue("LinkEntity<Classroom, ClassroomType>");
                });

            modelBuilder.Entity("ScheduleGo.Shared.ScheduleGoContext.Entities.LinkEntity<ScheduleGo.Domain.ScheduleGoContext.Entities.Classroom, ScheduleGo.Domain.ScheduleGoContext.Entities.Tag>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("LeftId")
                        .HasColumnName("Classroom")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RightId")
                        .HasColumnName("Tag")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RightId")
                        .IsUnique();

                    b.ToTable("ClassroomTag");

                    b.HasDiscriminator<string>("Discriminator").HasValue("LinkEntity<Classroom, Tag>");
                });

            modelBuilder.Entity("ScheduleGo.Shared.ScheduleGoContext.Entities.LinkEntity<ScheduleGo.Domain.ScheduleGoContext.Entities.Classroom, ScheduleGo.Domain.ScheduleGoContext.Entities.TimePeriod>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("LeftId")
                        .HasColumnName("Classroom")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RightId")
                        .HasColumnName("TimePeriod")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RightId")
                        .IsUnique();

                    b.ToTable("ClassroomTimePeriod");

                    b.HasDiscriminator<string>("Discriminator").HasValue("LinkEntity<Classroom, TimePeriod>");
                });

            modelBuilder.Entity("ScheduleGo.Shared.ScheduleGoContext.Entities.LinkEntity<ScheduleGo.Domain.ScheduleGoContext.Entities.Course, ScheduleGo.Domain.ScheduleGoContext.Entities.ClassroomType>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("LeftId")
                        .HasColumnName("Course")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RightId")
                        .HasColumnName("ClassroomType")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RightId")
                        .IsUnique();

                    b.ToTable("CourseClassroomType");

                    b.HasDiscriminator<string>("Discriminator").HasValue("LinkEntity<Course, ClassroomType>");
                });

            modelBuilder.Entity("ScheduleGo.Shared.ScheduleGoContext.Entities.LinkEntity<ScheduleGo.Domain.ScheduleGoContext.Entities.Course, ScheduleGo.Domain.ScheduleGoContext.Entities.Tag>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("LeftId")
                        .HasColumnName("Course")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RightId")
                        .HasColumnName("Tag")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RightId")
                        .IsUnique();

                    b.ToTable("CourseTag");

                    b.HasDiscriminator<string>("Discriminator").HasValue("LinkEntity<Course, Tag>");
                });

            modelBuilder.Entity("ScheduleGo.Shared.ScheduleGoContext.Entities.LinkEntity<ScheduleGo.Domain.ScheduleGoContext.Entities.Course, ScheduleGo.Domain.ScheduleGoContext.Entities.TimePeriod>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("LeftId")
                        .HasColumnName("Course")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RightId")
                        .HasColumnName("TimePeriod")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RightId")
                        .IsUnique();

                    b.ToTable("CourseTimePeriod");

                    b.HasDiscriminator<string>("Discriminator").HasValue("LinkEntity<Course, TimePeriod>");
                });

            modelBuilder.Entity("ScheduleGo.Shared.ScheduleGoContext.Entities.LinkEntity<ScheduleGo.Domain.ScheduleGoContext.Entities.Teacher, ScheduleGo.Domain.ScheduleGoContext.Entities.Course>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("LeftId")
                        .HasColumnName("Teacher")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RightId")
                        .HasColumnName("Course")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RightId")
                        .IsUnique();

                    b.ToTable("TeacherQualifiedCourse");

                    b.HasDiscriminator<string>("Discriminator").HasValue("LinkEntity<Teacher, Course>");
                });

            modelBuilder.Entity("ScheduleGo.Shared.ScheduleGoContext.Entities.LinkEntity<ScheduleGo.Domain.ScheduleGoContext.Entities.Teacher, ScheduleGo.Domain.ScheduleGoContext.Entities.TimePeriod>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("LeftId")
                        .HasColumnName("Teacher")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RightId")
                        .HasColumnName("TimePeriod")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RightId")
                        .IsUnique();

                    b.ToTable("TeacherPreferredPeriod");

                    b.HasDiscriminator<string>("Discriminator").HasValue("LinkEntity<Teacher, TimePeriod>");
                });

            modelBuilder.Entity("ScheduleGo.Domain.ScheduleGoContext.Entities.Links.ClassroomClassroomType", b =>
                {
                    b.HasBaseType("ScheduleGo.Shared.ScheduleGoContext.Entities.LinkEntity<ScheduleGo.Domain.ScheduleGoContext.Entities.Classroom, ScheduleGo.Domain.ScheduleGoContext.Entities.ClassroomType>");

                    b.HasIndex("LeftId")
                        .IsUnique();

                    b.HasDiscriminator().HasValue("ClassroomClassroomType");
                });

            modelBuilder.Entity("ScheduleGo.Domain.ScheduleGoContext.Entities.Links.ClassroomTag", b =>
                {
                    b.HasBaseType("ScheduleGo.Shared.ScheduleGoContext.Entities.LinkEntity<ScheduleGo.Domain.ScheduleGoContext.Entities.Classroom, ScheduleGo.Domain.ScheduleGoContext.Entities.Tag>");

                    b.HasIndex("LeftId");

                    b.HasDiscriminator().HasValue("ClassroomTag");
                });

            modelBuilder.Entity("ScheduleGo.Domain.ScheduleGoContext.Entities.Links.ClassroomTimePeriod", b =>
                {
                    b.HasBaseType("ScheduleGo.Shared.ScheduleGoContext.Entities.LinkEntity<ScheduleGo.Domain.ScheduleGoContext.Entities.Classroom, ScheduleGo.Domain.ScheduleGoContext.Entities.TimePeriod>");

                    b.HasIndex("LeftId");

                    b.HasDiscriminator().HasValue("ClassroomTimePeriod");
                });

            modelBuilder.Entity("ScheduleGo.Domain.ScheduleGoContext.Entities.Links.CourseClassroomType", b =>
                {
                    b.HasBaseType("ScheduleGo.Shared.ScheduleGoContext.Entities.LinkEntity<ScheduleGo.Domain.ScheduleGoContext.Entities.Course, ScheduleGo.Domain.ScheduleGoContext.Entities.ClassroomType>");

                    b.HasIndex("LeftId")
                        .IsUnique();

                    b.HasDiscriminator().HasValue("CourseClassroomType");
                });

            modelBuilder.Entity("ScheduleGo.Domain.ScheduleGoContext.Entities.Links.CourseTag", b =>
                {
                    b.HasBaseType("ScheduleGo.Shared.ScheduleGoContext.Entities.LinkEntity<ScheduleGo.Domain.ScheduleGoContext.Entities.Course, ScheduleGo.Domain.ScheduleGoContext.Entities.Tag>");

                    b.HasIndex("LeftId");

                    b.HasDiscriminator().HasValue("CourseTag");
                });

            modelBuilder.Entity("ScheduleGo.Domain.ScheduleGoContext.Entities.Links.CourseTimePeriod", b =>
                {
                    b.HasBaseType("ScheduleGo.Shared.ScheduleGoContext.Entities.LinkEntity<ScheduleGo.Domain.ScheduleGoContext.Entities.Course, ScheduleGo.Domain.ScheduleGoContext.Entities.TimePeriod>");

                    b.HasIndex("LeftId");

                    b.HasDiscriminator().HasValue("CourseTimePeriod");
                });

            modelBuilder.Entity("ScheduleGo.Domain.ScheduleGoContext.Entities.Links.TeacherPreferredCourse", b =>
                {
                    b.HasBaseType("ScheduleGo.Shared.ScheduleGoContext.Entities.LinkEntity<ScheduleGo.Domain.ScheduleGoContext.Entities.Teacher, ScheduleGo.Domain.ScheduleGoContext.Entities.Course>");

                    b.HasIndex("LeftId");

                    b.HasDiscriminator().HasValue("TeacherPreferredCourse");
                });

            modelBuilder.Entity("ScheduleGo.Domain.ScheduleGoContext.Entities.Links.TeacherQualifiedCourse", b =>
                {
                    b.HasBaseType("ScheduleGo.Shared.ScheduleGoContext.Entities.LinkEntity<ScheduleGo.Domain.ScheduleGoContext.Entities.Teacher, ScheduleGo.Domain.ScheduleGoContext.Entities.Course>");

                    b.HasIndex("LeftId")
                        .HasName("IX_TeacherQualifiedCourse_Teacher1");

                    b.HasDiscriminator().HasValue("TeacherQualifiedCourse");
                });

            modelBuilder.Entity("ScheduleGo.Domain.ScheduleGoContext.Entities.Links.TeacherAvailablePeriod", b =>
                {
                    b.HasBaseType("ScheduleGo.Shared.ScheduleGoContext.Entities.LinkEntity<ScheduleGo.Domain.ScheduleGoContext.Entities.Teacher, ScheduleGo.Domain.ScheduleGoContext.Entities.TimePeriod>");

                    b.HasIndex("LeftId");

                    b.HasDiscriminator().HasValue("TeacherAvailablePeriod");
                });

            modelBuilder.Entity("ScheduleGo.Domain.ScheduleGoContext.Entities.Links.TeacherPreferredPeriod", b =>
                {
                    b.HasBaseType("ScheduleGo.Shared.ScheduleGoContext.Entities.LinkEntity<ScheduleGo.Domain.ScheduleGoContext.Entities.Teacher, ScheduleGo.Domain.ScheduleGoContext.Entities.TimePeriod>");

                    b.HasIndex("LeftId")
                        .HasName("IX_TeacherPreferredPeriod_Teacher1");

                    b.HasDiscriminator().HasValue("TeacherPreferredPeriod");
                });

            modelBuilder.Entity("ScheduleGo.Shared.ScheduleGoContext.Entities.LinkEntity<ScheduleGo.Domain.ScheduleGoContext.Entities.Classroom, ScheduleGo.Domain.ScheduleGoContext.Entities.ClassroomType>", b =>
                {
                    b.HasOne("ScheduleGo.Domain.ScheduleGoContext.Entities.ClassroomType", "Right")
                        .WithOne()
                        .HasForeignKey("ScheduleGo.Shared.ScheduleGoContext.Entities.LinkEntity<ScheduleGo.Domain.ScheduleGoContext.Entities.Classroom, ScheduleGo.Domain.ScheduleGoContext.Entities.ClassroomType>", "RightId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("ScheduleGo.Shared.ScheduleGoContext.Entities.LinkEntity<ScheduleGo.Domain.ScheduleGoContext.Entities.Classroom, ScheduleGo.Domain.ScheduleGoContext.Entities.Tag>", b =>
                {
                    b.HasOne("ScheduleGo.Domain.ScheduleGoContext.Entities.Tag", "Right")
                        .WithOne()
                        .HasForeignKey("ScheduleGo.Shared.ScheduleGoContext.Entities.LinkEntity<ScheduleGo.Domain.ScheduleGoContext.Entities.Classroom, ScheduleGo.Domain.ScheduleGoContext.Entities.Tag>", "RightId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("ScheduleGo.Shared.ScheduleGoContext.Entities.LinkEntity<ScheduleGo.Domain.ScheduleGoContext.Entities.Classroom, ScheduleGo.Domain.ScheduleGoContext.Entities.TimePeriod>", b =>
                {
                    b.HasOne("ScheduleGo.Domain.ScheduleGoContext.Entities.TimePeriod", "Right")
                        .WithOne()
                        .HasForeignKey("ScheduleGo.Shared.ScheduleGoContext.Entities.LinkEntity<ScheduleGo.Domain.ScheduleGoContext.Entities.Classroom, ScheduleGo.Domain.ScheduleGoContext.Entities.TimePeriod>", "RightId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("ScheduleGo.Shared.ScheduleGoContext.Entities.LinkEntity<ScheduleGo.Domain.ScheduleGoContext.Entities.Course, ScheduleGo.Domain.ScheduleGoContext.Entities.ClassroomType>", b =>
                {
                    b.HasOne("ScheduleGo.Domain.ScheduleGoContext.Entities.ClassroomType", "Right")
                        .WithOne()
                        .HasForeignKey("ScheduleGo.Shared.ScheduleGoContext.Entities.LinkEntity<ScheduleGo.Domain.ScheduleGoContext.Entities.Course, ScheduleGo.Domain.ScheduleGoContext.Entities.ClassroomType>", "RightId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("ScheduleGo.Shared.ScheduleGoContext.Entities.LinkEntity<ScheduleGo.Domain.ScheduleGoContext.Entities.Course, ScheduleGo.Domain.ScheduleGoContext.Entities.Tag>", b =>
                {
                    b.HasOne("ScheduleGo.Domain.ScheduleGoContext.Entities.Tag", "Right")
                        .WithOne()
                        .HasForeignKey("ScheduleGo.Shared.ScheduleGoContext.Entities.LinkEntity<ScheduleGo.Domain.ScheduleGoContext.Entities.Course, ScheduleGo.Domain.ScheduleGoContext.Entities.Tag>", "RightId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("ScheduleGo.Shared.ScheduleGoContext.Entities.LinkEntity<ScheduleGo.Domain.ScheduleGoContext.Entities.Course, ScheduleGo.Domain.ScheduleGoContext.Entities.TimePeriod>", b =>
                {
                    b.HasOne("ScheduleGo.Domain.ScheduleGoContext.Entities.TimePeriod", "Right")
                        .WithOne()
                        .HasForeignKey("ScheduleGo.Shared.ScheduleGoContext.Entities.LinkEntity<ScheduleGo.Domain.ScheduleGoContext.Entities.Course, ScheduleGo.Domain.ScheduleGoContext.Entities.TimePeriod>", "RightId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("ScheduleGo.Shared.ScheduleGoContext.Entities.LinkEntity<ScheduleGo.Domain.ScheduleGoContext.Entities.Teacher, ScheduleGo.Domain.ScheduleGoContext.Entities.Course>", b =>
                {
                    b.HasOne("ScheduleGo.Domain.ScheduleGoContext.Entities.Course", "Right")
                        .WithOne()
                        .HasForeignKey("ScheduleGo.Shared.ScheduleGoContext.Entities.LinkEntity<ScheduleGo.Domain.ScheduleGoContext.Entities.Teacher, ScheduleGo.Domain.ScheduleGoContext.Entities.Course>", "RightId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("ScheduleGo.Shared.ScheduleGoContext.Entities.LinkEntity<ScheduleGo.Domain.ScheduleGoContext.Entities.Teacher, ScheduleGo.Domain.ScheduleGoContext.Entities.TimePeriod>", b =>
                {
                    b.HasOne("ScheduleGo.Domain.ScheduleGoContext.Entities.TimePeriod", "Right")
                        .WithOne()
                        .HasForeignKey("ScheduleGo.Shared.ScheduleGoContext.Entities.LinkEntity<ScheduleGo.Domain.ScheduleGoContext.Entities.Teacher, ScheduleGo.Domain.ScheduleGoContext.Entities.TimePeriod>", "RightId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("ScheduleGo.Domain.ScheduleGoContext.Entities.Links.ClassroomClassroomType", b =>
                {
                    b.HasOne("ScheduleGo.Domain.ScheduleGoContext.Entities.Classroom", "Left")
                        .WithOne("ClassroomType")
                        .HasForeignKey("ScheduleGo.Domain.ScheduleGoContext.Entities.Links.ClassroomClassroomType", "LeftId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ScheduleGo.Domain.ScheduleGoContext.Entities.Links.ClassroomTag", b =>
                {
                    b.HasOne("ScheduleGo.Domain.ScheduleGoContext.Entities.Classroom", "Left")
                        .WithMany("CategoryTags")
                        .HasForeignKey("LeftId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ScheduleGo.Domain.ScheduleGoContext.Entities.Links.ClassroomTimePeriod", b =>
                {
                    b.HasOne("ScheduleGo.Domain.ScheduleGoContext.Entities.Classroom", "Left")
                        .WithMany("AvailablePeriods")
                        .HasForeignKey("LeftId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ScheduleGo.Domain.ScheduleGoContext.Entities.Links.CourseClassroomType", b =>
                {
                    b.HasOne("ScheduleGo.Domain.ScheduleGoContext.Entities.Course", "Left")
                        .WithOne("ClassroomTypeNeeded")
                        .HasForeignKey("ScheduleGo.Domain.ScheduleGoContext.Entities.Links.CourseClassroomType", "LeftId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ScheduleGo.Domain.ScheduleGoContext.Entities.Links.CourseTag", b =>
                {
                    b.HasOne("ScheduleGo.Domain.ScheduleGoContext.Entities.Course", "Left")
                        .WithMany("CategoryTags")
                        .HasForeignKey("LeftId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ScheduleGo.Domain.ScheduleGoContext.Entities.Links.CourseTimePeriod", b =>
                {
                    b.HasOne("ScheduleGo.Domain.ScheduleGoContext.Entities.Course", "Left")
                        .WithMany("AvailablePeriods")
                        .HasForeignKey("LeftId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ScheduleGo.Domain.ScheduleGoContext.Entities.Links.TeacherPreferredCourse", b =>
                {
                    b.HasOne("ScheduleGo.Domain.ScheduleGoContext.Entities.Teacher", "Left")
                        .WithMany("PreferredCourses")
                        .HasForeignKey("LeftId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ScheduleGo.Domain.ScheduleGoContext.Entities.Links.TeacherQualifiedCourse", b =>
                {
                    b.HasOne("ScheduleGo.Domain.ScheduleGoContext.Entities.Teacher", "Left")
                        .WithMany("QualifiedCourses")
                        .HasForeignKey("LeftId")
                        .HasConstraintName("FK_TeacherQualifiedCourse_Teachers_Teacher1")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ScheduleGo.Domain.ScheduleGoContext.Entities.Links.TeacherAvailablePeriod", b =>
                {
                    b.HasOne("ScheduleGo.Domain.ScheduleGoContext.Entities.Teacher", "Left")
                        .WithMany("AvailablePeriods")
                        .HasForeignKey("LeftId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ScheduleGo.Domain.ScheduleGoContext.Entities.Links.TeacherPreferredPeriod", b =>
                {
                    b.HasOne("ScheduleGo.Domain.ScheduleGoContext.Entities.Teacher", "Left")
                        .WithMany("PreferredPeriods")
                        .HasForeignKey("LeftId")
                        .HasConstraintName("FK_TeacherPreferredPeriod_Teachers_Teacher1")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
